language: node_js
node_js:
  - stable
script: npm run lint && npm run build && npm run test
before_deploy:
  - ls
  - find -path ./node_modules -prune -o -print
deploy:
  provider: npm
  email: mitchell@de.rijcke.org
  api_key: ${NPM_TOKEN}
